language: python
python:
  - "2.7"
  - "3.4"
matrix:
  allow_failures:
    - python: "3.4"
install:
  - "pip install . --use-mirrors"
script: ./run_tests.sh
env:
  global:
    # NOTE: contains GH_TOKEN=xxx from github user gds-pp-ci
    secure: oJzXXHtKrMjqFAVS+sX/7C4A7PyusY3YKmzq3JGJRzUEtow37eOg6HzIWmCCrwWlL+vsdrlMr7Tw9ko3nfuEGG2+8OOSP67yfXK8Uy9N0XXVCYOpEPiwlPLkunWYl+WB4LLzf/DiYUjZX5O+Fo5etULf7me24gbd/mp1HQhba+Q=
after_success:
  - ./.travis_scripts/push_release_tag.sh
branches:
  except:
    - release
    - /^release_\d+$/
