import argparse
import os
import sys


class ParseError(StandardError):
    pass


def crontab_begin_comment(app_name):
    return '# Begin backdrop.collector jobs for %s' % app_name


def crontab_end_comment(app_name):
    return '# End backdrop.collector jobs for %s' % app_name


def remove_existing_crontab_for_app(crontab, app_name):
    new_crontab = []
    should_append = True
    for line in crontab:
        if line == crontab_begin_comment(app_name):
            should_append = False
        if should_append:
            new_crontab.append(line)
        if line == crontab_end_comment(app_name):
            should_append = True
    return new_crontab


def generate_crontab(current_crontab, path_to_jobs, path_to_app):
    """Returns a crontab with jobs from job path

    It replaces jobs previously generated by this function
    It preserves jobs not generated by this function
    """
    job_template = '{schedule} {python} {app_path}/collect.py ' \
                   '-q {app_path}/{query} -c {app_path}/{config} '

    app_name = os.path.basename(path_to_app)
    app_comment = "# %s" % app_name
    crontab = [
        line.strip() for line in current_crontab if app_comment not in line
    ]
    crontab = remove_existing_crontab_for_app(crontab, app_name)
    additional_crontab = []
    with open(path_to_jobs) as jobs:
        try:
            for job in jobs:
                schedule, query, config = job.strip().split(",")

                cronjob = job_template.format(
                    schedule=schedule,
                    python=sys.executable,
                    app_path=path_to_app,
                    query=query,
                    config=config,
                    app_name=app_name
                )

                additional_crontab.append(cronjob)
        except ValueError as e:
            raise ParseError(str(e))

    if additional_crontab:
        crontab.append(crontab_begin_comment(app_name))
        crontab.extend(additional_crontab)
        crontab.append(crontab_end_comment(app_name))

    return crontab


if __name__ == '__main__':
    current_crontab = sys.stdin.readlines()
    try:
        parser = argparse.ArgumentParser()
        parser.add_argument('path_to_app',
                            help='Path to where the application')
        parser.add_argument('path_to_jobs',
                            help='Path to the file where job templates are')

        args = parser.parse_args()

        crontab = generate_crontab(current_crontab,
                                   args.path_to_jobs,
                                   args.path_to_app)
        sys.stdout.write("\n".join(crontab) + "\n")
        sys.exit(0)
    except StandardError as e:
        sys.stderr.write(str(e))
        sys.stdout.write("\n".join(current_crontab))
        sys.exit(1)
